### ISSUE TITLE
cloudera agent salt install failing

### ISSUE THREAD

**Issue by charlesa101** [khrisrichardson/salt-states#20]
-> {% set minions  = salt['roles.dict']('cloudera-cm5-server') -%}

cloudera-scm-server works well except for the cloudera-scm-agents

it's giving this error ->
```---------
          ID: /etc/cloudera-scm-agent/config.ini
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'roles.dict'
     Started: 00:03:11.779556
    Duration: 91.8 ms
     Changes:   
----------
          ID: cloudera-cm5-agent
    Function: service.running
        Name: cloudera-scm-agent
      Result: False
     Comment: One or more requisite failed: cloudera-cm5-agent./etc/cloudera-scm-agent/config.ini
     Started: 
    Duration: 
     Changes:
```

@khrisrichardson: Thanks for the great job & sharing this for the community

**Comment by khrisrichardson** [comment]
Hi @charlesa101 There's an underlying assumption that this [module](https://github.com/khrisrichardson/salt-states/blob/master/salt/_modules/roles.py) will come along for the ride via saltutll.sync_modules or state.highstate.

That module includes a rudimentary form of service discovery, which assumes that a) a salt-master exists and b) that each of the minions have synced their "roles" grain to the mine. I had every intention of incorporating other forms of service discovery into the roles module, but my recent spate of employers has not provided incentive to give attention to such matters.

With immutable infrastructure and container orchestrators becoming the norm, dealing with service discovery at the configuration management layer of abstraction makes less sense than handing over that responsibility to the container orchestrator.

**Comment by charlesa101** [comment]
@khrisrichardson: cool, i see that now...thank you!
