### ISSUE TITLE
roles.dict throws exception for empty roles

### ISSUE THREAD

**Issue by kutschkem** [khrisrichardson/salt-states#9]
When the roles grain of a minion is empty, the roles.dict function throws the following exception:

    Passed invalid arguments: argument of type 'NoneType' is not iterable
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 138, in call
        ret['return'] = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/roles.py", line 52, in dict_
        if role in grains[minion].get('roles', []):
    TypeError: argument of type 'NoneType' is not iterable

What I did was I defined a roles grain, but left it empty:

    roles:

**Comment by khrisrichardson** [comment]
That's addressable with...

```
- if role in grains[minion].get('roles', []):
+ if role in grains.get(minion, {}).get('roles', []):
```

**Comment by khrisrichardson** [comment]
FYI - you may also have better luck setting roles to an empty list.

```
roles: []
```
